# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # Gurobi path
    env:
      GUROBI_HOME: ${{ github.workspace }}/gurobi1001/linux64
      LD_LIBRARY_PATH: ${{ github.workspace }}/gurobi1001/linux64/lib
      GRB_LICENSE_FILE: ${{ github.workspace }}/gurobi1001/linux64/gurobi.lic

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Cache Gurobi installation
      - name: Cache Gurobi installation
        id: cache-gurobi
        uses: actions/cache@v3
        with:
          path: ${{ env.GUROBI_HOME }}
          key: ${{ runner.os }}-gurobi

      # Runs a set of commands using the runners shell
      - name: Set up Gurobi and license
        # if: steps.cache-gurobi.outputs.cache-hit != 'true'
        run: |
          wget https://packages.gurobi.com/10.0/gurobi10.0.1_linux64.tar.gz
          tar -xzf gurobi10.0.1_linux64.tar.gz -C $GITHUB_WORKSPACE
          rm gurobi10.0.1_linux64.tar.gz

          # Set up environment variables
          echo -e "WLSACCESSID=d8784077-14a9-46a6-bd54-f57086ffc674\nWLSSECRET=2f79b3b8-7bdb-491c-b603-c82ce6f21566\nLICENSEID=928929" > $GRB_LICENSE_FILE
      
      - name: Run example script
        run: |
          cat $GRB_LICENSE_FILE
          $GUROBI_HOME/bin/gurobi_cl
          javac -cp .:$LD_LIBRARY_PATH/gurobi.jar Mip1.java
          java -cp .:$LD_LIBRARY_PATH/gurobi.jar Mip1


